### ISSUE TITLE
Feature Request : xmodem transfer

### ISSUE THREAD

**Issue by Isaac000** [yongchaofan/tinyTerm#2]
Any chance of adding xmodem transfer to Serial connections?

**Comment by yongchaofan** [comment]
Yes, it's definitely possible, I will be thinking about for a few days, mainly to decide if it should be part of the terminal program or implemented as a script.

**Comment by yongchaofan** [comment]
Version 1.8 release with xmodem send support, simple drag&drop a file to terminal window to send with xmodem on serial connection

**Comment by Isaac000** [comment]
Thank you! This will be very useful for me

**Comment by Isaac000** [comment]
Hmm...unfortunately the xmodem send doesn't seem to work here.
I have to connect at 230400 (this is what the dev board I'm using supports).
After dragging and dropping file into the window, I see it say "xmodem" then shortly CRC and then it hangs. The dev board is not hung up, if I disconnect and reconnect tinyTerm it's fine but the file never gets uploaded.
Might be good to have this scriptable and get more debug messages to see what's going on. I suppose I could try compiling from source myself?

**Comment by yongchaofan** [comment]
By "hangs" you mean tinyTerm is not displaying anything, but menus and mouse clicks still works, right?

The xmodem function will semd the first data block after showing CRC, then wait for ACK, if none received in 10 seconds it will resend and display a letter "R", after 6 consecutive resends it will abort.

That is the spec of basic xmodem protocol, is your devel board expect that? or some extension like ymodem?

Of course you can try modify and compile the source code yourself, another idea is to get a serial port debugger and log what going on between tinyTerm and your devel board.

Thanks,
Yongchao

**Comment by Isaac000** [comment]
That is correct, tinyTerm is still responsive but no result back from UART. I know the dev board is not down because I can connect with another terminal or simply disconnect/connect with tinyTerm and displays just fine. I can wait a "long" time with tinyTerm but it never aborts...and I never see the letter R.
The devel board is definitely using xmodem. The xmodem uploads work fine on my devel board with TeraTerm or PuTTY (I don't use either of them because they are not really scriptable).

**Comment by yongchaofan** [comment]
https://freeserialanalyzer.com/

seems to be a working serial port debugger, if you can log a session using tinyTerm, and another session with Putty, I will try to figure out what's missing.

Thanks,
Yongchao

**Comment by yongchaofan** [comment]
I don't have any dev board on hand, so this xmodem function was put together over weekend, and tested using two computers back to back, one of them is running WindowsXP with HyperTerminal, with tinyTerm sending and HyperTerminal receiving

I will have the test setup again this coming weekend, to test tinyTerm against teraTerm or Putty

Thanks,
Yongchao
